apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: currency-microservice
  name: currency-microservice
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency-microservice
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: currency-microservice
    spec:
      containers:
        - image: asibrahim/asimosiprepo:jenkins-FirstTestPipiline-16
          imagePullPolicy: Always
          name: currency-microservice
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: currency-microservice
  name: currency-microservice
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 51000
  selector:
    app: currency-microservice
  sessionAffinity: None
  type: ClusterIP